/**
 * Agreement content model — Phase 0.1 (2026-06-14).
 *
 * Single source of truth for the three vendor agreements. The same structured
 * content renders two ways:
 *   - in-app read view (RN <AgreementBody/> component) — Phase 0.3
 *   - signed PDF via expo-print HTML — Phase 0.2
 *
 * Legal text is transcribed VERBATIM from the founder-team final PDFs:
 *   Final_Vendor Agreement - For Groceries.pdf      → standard body, 2% commission
 *   Final_Vendor Agreement - For Other Stores.pdf   → standard body, 5% commission
 *   Final_Vendor Agreement - For restaurants.pdf    → restaurant body
 * Grocery and Other Stores are byte-identical except the section 3.3 commission
 * line, so they share ONE standard body with the commission text parameterized.
 *
 * Fidelity notes:
 *  - The source numbering quirk is preserved as authored: it jumps 33 → 35
 *    (there is no section 34).
 *  - The manual signature-line placeholders at the foot of each PDF are NOT
 *    included here — they are replaced by the generated Execution block (0.2).
 *  - The personalized parties recital + the Merchant Details header are
 *    generated by the builder (0.2) from MerchantAgreementData; the bodies hold
 *    only the fixed legal clauses + the per-type "by signing" binding clause.
 *  - Curly apostrophes/quotes in the source are normalized to straight marks;
 *    no wording is changed.
 */

/** A sub-clause within a section. */
export interface Clause {
  /** Sub-clause number as authored, e.g. "1.1", "3.3". Omitted for an unnumbered lead/trailing paragraph. */
  n?: string;
  /** Optional sub-clause heading, e.g. "Platform Services". */
  title?: string;
  /** Body paragraph(s). May contain "\n\n" to separate multiple paragraphs, or "\n" for address-style lines. */
  text?: string;
  /** Bulleted list, rendered after `text`. */
  bullets?: string[];
}

/** A numbered top-level section. */
export interface Section {
  /** Section number as authored, e.g. "1", "33", "35". */
  n: string;
  title: string;
  clauses: Clause[];
}

/** The fixed legal content of an agreement (no merchant-specific merge fields). */
export interface AgreementBody {
  /** The per-type "By signing this Agreement..." binding paragraph. */
  bindingClause: string;
  sections: Section[];
}

/** Which of the three agreements a merchant gets (derived from their vertical). */
export type AgreementType = 'grocery' | 'otherStores' | 'restaurant';

/**
 * Merge-fields for the Merchant Details header + Execution block. Every field
 * is sourced from data already captured at signup (Identity + Store + KYC).
 */
export interface MerchantAgreementData {
  businessName: string;
  storeCategory: string;
  signatoryName: string;
  designation: string;
  placeOfBusiness: string;
  pan: string;
  /** Full Aadhaar number; the renderer masks to the last 4 digits. */
  aadhaar?: string;
  gstin?: string;
  fssai?: string;
  phone: string;
  email: string;
  /** Display reference, e.g. "PAS-7C575305". */
  merchantId: string;
  /** Display date of acceptance, e.g. "14 June 2026". */
  acceptanceDate: string;
}
