/**
 * signupStyles — shared StyleSheet for the merchant signup flow.
 *
 * 2026-06-04 (Phase 1.7.0): Extracted verbatim from app/(auth)/signup.tsx's
 * local `styles` block so that per-step components (Phase 1.7.A-G) can import
 * the same look-and-feel without re-declaring or prop-drilling styles. NO
 * style values changed.
 *
 * The orchestrator (signup.tsx) and each step component (StepIdentity,
 * StepStore, StepPhotos, StepBranches, StepKyc, StepSubscription, StepReview)
 * import this `styles` and consume the keys they need.
 */

import { StyleSheet } from 'react-native';
import { Colors } from '../../../../constants/Colors';

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#F9FAFB' },
    header: { backgroundColor: '#FFFFFF', padding: 16, borderBottomWidth: 1, borderBottomColor: '#E5E7EB' },
    stepContainer: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8 },
    stepCircle: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#F3F4F6', justifyContent: 'center', alignItems: 'center' },
    stepPill: { paddingHorizontal: 18, height: 36, borderRadius: 18, backgroundColor: Colors.primary, justifyContent: 'center', alignItems: 'center' },
    stepPillText: { fontSize: 13, fontWeight: '700', color: '#FFFFFF', letterSpacing: 0.5 },
    stepNumber: { fontSize: 14, fontWeight: '600', color: '#9CA3AF' },
    content: { flex: 1 },
    contentContainer: { flexGrow: 1, backgroundColor: '#F9FAFB' },
    card: { backgroundColor: '#FFFFFF', borderRadius: 16, padding: 20, marginBottom: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 4, elevation: 2 },
    cardHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 20 },
    cardTitle: { fontSize: 16, fontWeight: '600', color: '#111827', marginLeft: 8, flex: 1 },
    inputGroup: { marginBottom: 16 },
    label: { fontSize: 14, fontWeight: '500', color: '#374151', marginBottom: 8 },
    required: { color: '#EF4444' },
    input: { height: 48, borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 12, paddingHorizontal: 16, fontSize: 16, color: '#111827', backgroundColor: '#FFFFFF' },
    textArea: { height: 80, paddingTop: 12, textAlignVertical: 'top' },
    selectInput: { height: 48, borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 12, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    selectText: { fontSize: 16, color: '#111827' },
    selectPlaceholder: { fontSize: 16, color: '#9CA3AF' },
    pickerContainer: { marginTop: 8, borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 12, backgroundColor: '#FFFFFF' },
    pickerItem: { paddingVertical: 12, paddingHorizontal: 16, borderBottomWidth: 1, borderBottomColor: '#F3F4F6' },
    pickerItemText: { fontSize: 15, color: '#374151' },
    locationButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', height: 48, borderWidth: 1, borderColor: Colors.primary + '30', borderRadius: 12, backgroundColor: Colors.primary + '08', marginBottom: 12 },
    locationButtonText: { fontSize: 14, fontWeight: '600', color: Colors.primary, marginLeft: 8 },
    coordinatesText: { fontSize: 13, color: '#6B7280', textAlign: 'center', marginBottom: 16 },
    checkboxRow: { flexDirection: 'row', alignItems: 'flex-start' },
    checkbox: { width: 22, height: 22, borderRadius: 6, borderWidth: 2, borderColor: '#D1D5DB', justifyContent: 'center', alignItems: 'center', marginRight: 12, marginTop: 2 },
    checkboxChecked: { backgroundColor: Colors.primary, borderColor: Colors.primary },
    checkboxLabel: { fontSize: 16, fontWeight: '600', color: '#111827' },
    checkboxHint: { fontSize: 13, color: '#6B7280', marginTop: 4 },
    addButton: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8, backgroundColor: Colors.primary + '08' },
    addButtonText: { fontSize: 13, fontWeight: '600', color: Colors.primary, marginLeft: 4 },
    emptyState: { alignItems: 'center', paddingVertical: 32 },
    emptyText: { fontSize: 14, color: '#9CA3AF' },
    emptyCard: { backgroundColor: '#F9FAFB', borderRadius: 16, padding: 40, alignItems: 'center', borderWidth: 1, borderColor: '#E5E7EB' },
    emptyCardTitle: { fontSize: 16, fontWeight: '600', color: '#6B7280', marginTop: 12 },
    branchCard: { backgroundColor: '#F9FAFB', borderRadius: 12, padding: 16, marginBottom: 12 },
    branchHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
    branchTitle: { fontSize: 13, fontWeight: '700', color: '#6B7280' },
    successCard: { alignItems: 'center', backgroundColor: '#ECFDF5', borderWidth: 1, borderColor: '#A7F3D0' },
    successTitle: { fontSize: 18, fontWeight: '700', color: '#065F46', marginTop: 12 },
    successText: { fontSize: 14, color: '#047857', textAlign: 'center', marginTop: 8 },
    reviewTitle: { fontSize: 16, fontWeight: '600', color: '#111827', marginBottom: 16 },
    reviewRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#F3F4F6' },
    reviewLabel: { fontSize: 14, color: '#6B7280' },
    reviewValue: { fontSize: 14, fontWeight: '600', color: '#111827' },
    footer: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#FFFFFF', paddingHorizontal: 16, paddingVertical: 12, borderTopWidth: 1, borderTopColor: '#E5E7EB' },
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', padding: 20 },
    modalContent: { backgroundColor: '#fff', borderRadius: 16, padding: 20, maxHeight: 400 },
    modalTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 16, textAlign: 'center' },
    modalItem: { paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: '#F3F4F6', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    modalItemText: { fontSize: 16, color: '#374151' },
    modalItemTextActive: { color: Colors.primary, fontWeight: '600' },
    modalCloseBtn: { marginTop: 16, padding: 12, backgroundColor: '#F3F4F6', borderRadius: 12, alignItems: 'center' },
    modalCloseText: { fontWeight: '600', color: '#374151' },
    divider: { height: 1, backgroundColor: '#E5E7EB', marginVertical: 20 },
    sectionHeader: { fontSize: 16, fontWeight: '600', color: '#111827', marginBottom: 16 },
    backButton: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10, paddingHorizontal: 4 },
    backButtonText: { fontSize: 15, color: '#6B7280', marginLeft: 4 },
    stepCounter: { fontSize: 13, color: '#9CA3AF' },
    nextButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.primary, paddingHorizontal: 20, paddingVertical: 12, borderRadius: 12 },
    nextButtonText: { fontSize: 15, fontWeight: '600', color: '#FFFFFF', marginRight: 4 },
    buttonDisabled: { opacity: 0.6 },
    uploadButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', padding: 12, borderWidth: 1, borderColor: Colors.primary + '30', borderRadius: 8, backgroundColor: Colors.primary + '08', marginBottom: 12 },
    uploadText: { marginLeft: 8, color: Colors.primary, fontWeight: '600', fontSize: 13 },
    photoGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginTop: 12 },
    photoWrapper: { width: 80, height: 80, position: 'relative' },
    photoBox: { width: '100%', height: '100%', backgroundColor: '#F3F4F6', borderRadius: 12, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: '#E5E7EB' },
    removePhoto: { position: 'absolute', top: -8, right: -8, backgroundColor: '#FFFFFF', borderRadius: 10 },
    addPhotoBox: { width: 80, height: 80, backgroundColor: Colors.primary + '08', borderRadius: 12, justifyContent: 'center', alignItems: 'center', borderStyle: 'dashed', borderWidth: 2, borderColor: Colors.primary + '30' },
    addPhotoText: { fontSize: 10, color: Colors.primary, fontWeight: '600', marginTop: 4 },
    photoCounter: { fontSize: 12, color: '#9CA3AF', marginTop: 12, textAlign: 'center' },
    turnoverGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    turnoverButton: { flex: 1, minWidth: '45%', height: 44, borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 10, justifyContent: 'center', alignItems: 'center', backgroundColor: '#FFFFFF' },
    turnoverButtonActive: { borderColor: Colors.primary, backgroundColor: Colors.primary + '08' },
    turnoverTextOption: { fontSize: 14, color: '#374151', fontWeight: '500' },
    turnoverTextActive: { color: Colors.primary, fontWeight: '700' },
    authLogoContainer: {
        alignItems: 'center',
        marginBottom: 24,
        marginTop: 8,
    },
    authLogo: {
        width: 100,
        height: 100,
        marginBottom: 12,
    },
    authTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#111827',
        marginBottom: 4,
    },
    authSubtitle: {
        fontSize: 14,
        color: '#6B7280',
        textAlign: 'center',
    },
});
