-- Phase 2 · Step 3 — seed CategoryMapping rows (BLINKIT 643 pairs) — 2026-06-15
-- STAGED. Apply via prisma db execute. Idempotent (ON CONFLICT UPDATE). Resolves
-- vertical/subcat by NAME at apply time. PENDING_DECISION rows (NULL/Specials/Digital/
-- tobacco) get NULL ids and never reach the storefront.
INSERT INTO public."CategoryMapping" (id, source_platform, source_category, source_subcategory, vertical_id, category_id, status, "createdAt","updatedAt")
SELECT gen_random_uuid(),'BLINKIT',s.cat,s.subcat,ver.id,t2.id,s.status,now(),now()
FROM (VALUES
  ('Pharma & Wellness','Prescription Medicines','Pharmacy & Wellness','OTC Medicines','ACTIVE'),
  ('Fashion & Accessories','Jewellery','Fashion & Apparel','Accessories & Jewelry','ACTIVE'),
  ('Electronics & Electricals','Appliances','Electronics & Accessories','Smart Gadgets','ACTIVE'),
  ('Electronics & Electricals','Electronic Accessories','Electronics & Accessories','Cables & Chargers','ACTIVE'),
  ('Fashion & Accessories','Fashion Accesssories','Fashion & Apparel','Accessories & Jewelry','ACTIVE'),
  ('Beauty & Cosmetics','Tools & Accessories','Beauty & Personal Care','Tools & Accessories','ACTIVE'),
  ('Home Furnishing & Decor','Home Furnishing','Home & Lifestyle','Bedding & Towels','ACTIVE'),
  ('Home & Office','Kitchen & Dining Needs','Home & Lifestyle','Kitchenware','ACTIVE'),
  ('Sweet Tooth','Ice Cream & Frozen Dessert','Bakeries & Desserts','Ice Cream & Frozen Desserts','ACTIVE'),
  ('Munchies','Chips & Crisps','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Beauty & Cosmetics','Face Care','Beauty & Personal Care','Skincare','ACTIVE'),
  ('Home Furnishing & Decor','Festive & Occasion Needs','Pooja & Festive Needs','Festive & Occasion','ACTIVE'),
  ('Dry Fruits, Masala & Oil','Powdered Spice','Grocery & Kirana','Masalas & Spices','ACTIVE'),
  ('Dry Fruits, Masala & Oil','Dry Fruits','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Home Furnishing & Decor','Home Decor','Home & Lifestyle','Home Decor','ACTIVE'),
  ('Home Furnishing & Decor','Spiritual & Religious Needs','Pooja & Festive Needs','Spiritual & Religious','ACTIVE'),
  ('Beauty & Cosmetics','Lip Cosmetics','Beauty & Personal Care','Makeup & Cosmetics','ACTIVE'),
  ('Electronics & Electricals','Audio & Accessories','Electronics & Accessories','Earphones & Audio','ACTIVE'),
  ('Home & Office','Festive & Occasion Needs','Pooja & Festive Needs','Festive & Occasion','ACTIVE'),
  ('Sweet Tooth','Indian Sweets','Bakeries & Desserts','Artisanal Sweets','ACTIVE'),
  ('Toys & Games','Cars & Vehicles','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Fashion & Accessories','Men''s Innerwear & Loungewear','Fashion & Apparel','Men''s Clothing','ACTIVE'),
  ('Dry Fruits, Masala & Oil','Oil','Grocery & Kirana','Cooking Oil & Ghee','ACTIVE'),
  ('Atta, Rice & Dal','Rice','Grocery & Kirana','Rice & Grains','ACTIVE'),
  ('Toys & Games','Baby & Toddler','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Personal Care','Hair Care','Beauty & Personal Care','Hair Care','ACTIVE'),
  ('Fashion & Accessories','Women''s Innerwear & Loungewear','Fashion & Apparel','Women''s Clothing','ACTIVE'),
  ('Stationery Needs','School Essentials','Stationery, Gifting & Toys','School Supplies','ACTIVE'),
  ('Home Furnishing & Decor','Flowers, Plants & Gardening','Home & Lifestyle','Gardening Essentials','ACTIVE'),
  ('Beauty & Cosmetics','Hair Styling & Treatment','Beauty & Personal Care','Hair Care','ACTIVE'),
  ('Pharma & Wellness','Non-Prescription Medicines','Pharmacy & Wellness','OTC Medicines','ACTIVE'),
  ('Home Furnishing & Decor','Home Improvement','Hardware & Plumbing','Home Improvement & Tools','ACTIVE'),
  ('Munchies','Namkeen Snacks','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Home & Office','Pooja Needs','Pooja & Festive Needs','Pooja Essentials','ACTIVE'),
  ('Electronics & Electricals','Decorative Lights & Lamps','Electronics & Accessories','Smart Gadgets','ACTIVE'),
  ('Pet Care','Dog Needs','Pet Care & Supplies','Dog Food','ACTIVE'),
  ('Dairy & Breakfast','Bread & Pav','Grocery & Kirana','Ready-to-Eat','ACTIVE'),
  ('Dry Fruits, Masala & Oil','Whole Spices','Grocery & Kirana','Masalas & Spices','ACTIVE'),
  ('Bakery & Biscuits','Cookies','Bakeries & Desserts','Cookies & Biscuits','ACTIVE'),
  ('Fashion & Accessories','Luggage & Travel Bags','Fashion & Apparel','Accessories & Jewelry','ACTIVE'),
  ('Beauty & Cosmetics','Face Cosmetics','Beauty & Personal Care','Makeup & Cosmetics','ACTIVE'),
  ('Home & Office','Home Decor','Home & Lifestyle','Home Decor','ACTIVE'),
  ('Baby Care','Baby Accessories & Apparel','Fashion & Apparel','Kids'' Wear','ACTIVE'),
  ('Kitchen & Dining','Kitchen Accessories','Home & Lifestyle','Kitchenware','ACTIVE'),
  ('Pharma & Wellness','Sexual Wellness','Pharmacy & Wellness','Sexual Wellness','ACTIVE'),
  ('Cleaning Essentials','Cleaning Tools','Home & Lifestyle','Cleaning Supplies','ACTIVE'),
  ('Fashion & Accessories','Men''s Westernwear','Fashion & Apparel','Men''s Clothing','ACTIVE'),
  ('Pharma & Wellness','Health & Wellness Supplements','Pharmacy & Wellness','Vitamins & Supplements','ACTIVE'),
  ('Home & Office','Home Furnishing','Home & Lifestyle','Bedding & Towels','ACTIVE'),
  ('Personal Care','Feminine Care','Beauty & Personal Care','Feminine Care','ACTIVE'),
  ('Kitchen & Dining','Dining and Serveware','Home & Lifestyle','Kitchenware','ACTIVE'),
  ('Sweet Tooth','Chocolates','Bakeries & Desserts','Artisanal Sweets','ACTIVE'),
  ('Beauty & Cosmetics','Fragrance','Beauty & Personal Care','Fragrances','ACTIVE'),
  ('Pet Care','Cat Needs','Pet Care & Supplies','Cat Food','ACTIVE'),
  ('Books','Children''s Books','Stationery, Gifting & Toys','Books','ACTIVE'),
  ('Personal Care','Bathing','Beauty & Personal Care','Bath & Body','ACTIVE'),
  ('Dry Fruits, Masala & Oil','Dates & Seeds','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Home Furnishing & Decor','Tissues & Disposables','Home & Lifestyle','Cleaning Supplies','ACTIVE'),
  ('Personal Care','Face Cleaning','Beauty & Personal Care','Skincare','ACTIVE'),
  ('Personal Care','Sunscreen','Beauty & Personal Care','Skincare','ACTIVE'),
  ('Fashion & Accessories','Men''s Footwear','Fashion & Apparel','Footwear','ACTIVE'),
  ('Stationery Needs','Gifting Needs','Stationery, Gifting & Toys','Gifting & Packing','ACTIVE'),
  ('Vegetables & Fruits','Exotics','Fresh Items','Exotic Fruits & Greens','ACTIVE'),
  ('Digital Goods','E-Cards','','','PENDING_DECISION'),
  ('Stationery Needs','Arts & Crafts','Stationery, Gifting & Toys','Art & Craft Supplies','ACTIVE'),
  ('Home & Office','Sports & Fitness','Sports & Fitness','Fitness Equipment & Gear','ACTIVE'),
  ('Personal Care','Oral Care','Beauty & Personal Care','Oral Care','ACTIVE'),
  ('Dry Fruits, Masala & Oil','Ghee & Vanaspati','Grocery & Kirana','Cooking Oil & Ghee','ACTIVE'),
  ('Kitchen & Dining','Bottles & Flasks','Home & Lifestyle','Kitchenware','ACTIVE'),
  ('Personal Care','Face & Body Moisturizers','Beauty & Personal Care','Skincare','ACTIVE'),
  ('Cold Drinks & Juices','Soda & Mixers','Grocery & Kirana','Beverages','ACTIVE'),
  ('Fashion & Accessories','Men''s Ethnic Wear','Fashion & Apparel','Men''s Clothing','ACTIVE'),
  ('Home & Office','Tissues & Disposables','Home & Lifestyle','Cleaning Supplies','ACTIVE'),
  ('Kitchen & Dining','Storage & Containers','Home & Lifestyle','Storage & Organizers','ACTIVE'),
  ('Instant & Frozen Food','Energy Bars','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Toys & Games','Indoor & Outdoor Play','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Bakery & Biscuits','Cakes & Rolls','Bakeries & Desserts','Cakes & Pastries','ACTIVE'),
  ('Instant & Frozen Food','Noodles','Grocery & Kirana','Ready-to-Eat','ACTIVE'),
  ('Fashion & Accessories','Women''s Handbags','Fashion & Apparel','Accessories & Jewelry','ACTIVE'),
  ('Cold Drinks & Juices','Soft Drinks','Grocery & Kirana','Beverages','ACTIVE'),
  ('Pet Care','Accessories & Other Supplies','Pet Care & Supplies','Toys & Accessories','ACTIVE'),
  ('Home Furnishing & Decor','Sports & Fitness','Sports & Fitness','Fitness Equipment & Gear','ACTIVE'),
  ('Sauces & Spreads','Indian Chutney & Pickle','Grocery & Kirana','General','ACTIVE'),
  ('Munchies','Bhujia & Mixtures','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Cleaning Essentials','Fresheners','Home & Lifestyle','Repellents & Fresheners','ACTIVE'),
  ('Atta, Rice & Dal','Millet & Other Flours','Grocery & Kirana','Atta','ACTIVE'),
  ('Toys & Games','Soft Toys','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Munchies','Makhana & More','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Fashion & Accessories','Men''s Sports Wear','Fashion & Apparel','Men''s Clothing','ACTIVE'),
  ('Toys & Games','Art & Craft','Stationery, Gifting & Toys','Art & Craft Supplies','ACTIVE'),
  ('Home & Office','Flowers, Plants & Gardening','Home & Lifestyle','Gardening Essentials','ACTIVE'),
  ('Dry Fruits, Masala & Oil','Salt, Sugar & Jaggery','Grocery & Kirana','Staples & Pulse','ACTIVE'),
  ('Beauty & Cosmetics','Eye Makeup','Beauty & Personal Care','Makeup & Cosmetics','ACTIVE'),
  ('Fashion & Accessories','Bags','Fashion & Apparel','Accessories & Jewelry','ACTIVE'),
  ('Pharma & Wellness','Pure OTC','Pharmacy & Wellness','OTC Medicines','ACTIVE'),
  ('Home Furnishing & Decor','Bathroom Essentials','Home & Lifestyle','Bathroom Accessories','ACTIVE'),
  ('Beauty & Cosmetics','Hair Care','Beauty & Personal Care','Hair Care','ACTIVE'),
  ('Vegetables & Fruits','Fresh Fruits','Fresh Items','Fresh Fruits','ACTIVE'),
  ('Stationery Needs','Pens & Pencils','Stationery, Gifting & Toys','Pens & Markers','ACTIVE'),
  ('Dairy & Breakfast','Curd & Yogurt','Grocery & Kirana','Dairy & Milk','ACTIVE'),
  ('Beauty & Cosmetics','Nail Cosmetics','Beauty & Personal Care','Makeup & Cosmetics','ACTIVE'),
  ('Sweet Tooth','Candies & Gum','Bakeries & Desserts','Candies & Confections','ACTIVE'),
  ('Fashion & Accessories','Women''s Footwear','Fashion & Apparel','Footwear','ACTIVE'),
  ('Pharma & Wellness','Protein and Workout Supplements','Pharmacy & Wellness','Vitamins & Supplements','ACTIVE'),
  ('Home & Office','Stationery Needs','Stationery, Gifting & Toys','Office Supplies','ACTIVE'),
  ('Atta, Rice & Dal','Toor, Urad & Chana','Grocery & Kirana','Dal & Pulses','ACTIVE'),
  ('Atta, Rice & Dal','Poha, Daliya & Other Grains','Grocery & Kirana','Rice & Grains','ACTIVE'),
  ('Cleaning Essentials','Repellents','Home & Lifestyle','Repellents & Fresheners','ACTIVE'),
  ('Beauty & Cosmetics','Lip & Eye Care','Beauty & Personal Care','Makeup & Cosmetics','ACTIVE'),
  ('Home & Office','Electronic Accessories','Home & Lifestyle','Home Essentials','ACTIVE'),
  ('Chicken, Meat & Fish','Chicken','Fresh Items','Chicken & Poultry','ACTIVE'),
  ('Tea, Coffee & Health Drinks','Coffee','Grocery & Kirana','Beverages','ACTIVE'),
  ('Electronics & Electricals','Hardware & Electricals','Hardware & Plumbing','Hardware & Fittings','ACTIVE'),
  ('Cold Drinks & Juices','Energy Drinks','Grocery & Kirana','Beverages','ACTIVE'),
  ('Baby Care','Diapers & More','Pharmacy & Wellness','Baby Diapers & Wipes','ACTIVE'),
  ('Home & Office','Bathroom Essentials','Home & Lifestyle','Bathroom Accessories','ACTIVE'),
  ('Kitchen & Dining','Cookware & Sets','Home & Lifestyle','Kitchenware','ACTIVE'),
  ('Personal Care','Deodorant & Talc','Beauty & Personal Care','Deodorants & Talc','ACTIVE'),
  ('Atta, Rice & Dal','Atta','Grocery & Kirana','Atta','ACTIVE'),
  ('Instant & Frozen Food','Ready to Cook & Eat','Grocery & Kirana','Ready-to-Eat','ACTIVE'),
  ('Stationery Needs','Notebooks & Diaries','Stationery, Gifting & Toys','Notebooks & Diaries','ACTIVE'),
  ('Kitchen & Dining','Mugs & Glasses','Home & Lifestyle','Kitchenware','ACTIVE'),
  ('Pharma & Wellness','Vitamins & Daily Nutrition','Pharmacy & Wellness','Vitamins & Supplements','ACTIVE'),
  ('NULL','NULL','','','PENDING_DECISION'),
  ('Cleaning Essentials','Floor & Surface Cleaners','Home & Lifestyle','Cleaning Supplies','ACTIVE'),
  ('Atta, Rice & Dal','Rajma, Chhole & Others','Grocery & Kirana','Dal & Pulses','ACTIVE'),
  ('Vegetables & Fruits','Trusted Organic','Fresh Items','Fresh Produce','ACTIVE'),
  ('Toys & Games','Card, Board & Tabletop Games','Stationery, Gifting & Toys','Board Games','ACTIVE'),
  ('Stationery Needs','Office Supplies','Stationery, Gifting & Toys','Office Supplies','ACTIVE'),
  ('Masala, Oil & More','Powdered Masala','Grocery & Kirana','Masalas & Spices','ACTIVE'),
  ('Personal Care','Facial Care','Beauty & Personal Care','Skincare','ACTIVE'),
  ('Atta, Rice & Dal','Besan, Sooji & Maida','Grocery & Kirana','Atta','ACTIVE'),
  ('Books','Non Fiction Books','Stationery, Gifting & Toys','Books','ACTIVE'),
  ('Dairy & Breakfast','Eggs','Grocery & Kirana','Dairy & Milk','ACTIVE'),
  ('Magazines','News & Current Affairs','Stationery, Gifting & Toys','Magazines','ACTIVE'),
  ('Kitchen & Dining','Lunch Boxes','Home & Lifestyle','Kitchenware','ACTIVE'),
  ('Cold Drinks & Juices','Fruit Juice','Grocery & Kirana','Beverages','ACTIVE'),
  ('Tea, Coffee & Health Drinks','Lassi, Shakes & More','Grocery & Kirana','Lassi & Shakes','ACTIVE'),
  ('Tea, Coffee & Milk Drinks','Lassi, Shakes & More','Grocery & Kirana','Lassi & Shakes','ACTIVE'),
  ('Baby Care','Feeding Essentials','Pharmacy & Wellness','Baby Feeding Essentials','ACTIVE'),
  ('Personal Care','Men''s Grooming','Beauty & Personal Care','Men''s Grooming','ACTIVE'),
  ('Pharma & Wellness','Wound Care And Pain Relief','Pharmacy & Wellness','Pain Relief','ACTIVE'),
  ('Tea, Coffee & Health Drinks','Tea','Grocery & Kirana','Beverages','ACTIVE'),
  ('Beauty & Cosmetics','Beauty and Makeup','Beauty & Personal Care','Makeup & Cosmetics','ACTIVE'),
  ('Vegetables & Fruits','Fresh Vegetables','Fresh Items','Fresh Vegetables','ACTIVE'),
  ('Home & Office','Home Decor & Storage','Home & Lifestyle','Storage & Organizers','ACTIVE'),
  ('Tea, Coffee & Milk Drinks','Tea','Grocery & Kirana','Beverages','ACTIVE'),
  ('Toys & Games','Puzzles & Cubes','Stationery, Gifting & Toys','Board Games','ACTIVE'),
  ('Sweet Tooth','Chocolate Packs','Bakeries & Desserts','Artisanal Sweets','ACTIVE'),
  ('Fashion & Accessories','Women''s Ethnic Wear','Fashion & Apparel','Women''s Clothing','ACTIVE'),
  ('Tea, Coffee & Milk Drinks','Coffee','Grocery & Kirana','Beverages','ACTIVE'),
  ('Beauty & Cosmetics','Gift & Kits','Beauty & Personal Care','Gift Sets & Kits','ACTIVE'),
  ('Cold Drinks & Juices','Concentrates & Syrups','Grocery & Kirana','Beverages','ACTIVE'),
  ('Bakery & Biscuits','Gourmet Bakery','Bakeries & Desserts','Artisanal Sweets','ACTIVE'),
  ('Toys & Games','Building Blocks & Sets','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Sauces & Spreads','Cooking Sauces & Vinegar','Grocery & Kirana','General','ACTIVE'),
  ('Pharma & Wellness','Health & Ortho Supports','Pharmacy & Wellness','Health Supports & Ortho','ACTIVE'),
  ('Atta, Rice & Dal','Moong & Masoor','Grocery & Kirana','Dal & Pulses','ACTIVE'),
  ('Organic & Premium','Beverages','Grocery & Kirana','Beverages','ACTIVE'),
  ('Cleaning Essentials','Liquid Detergents','Home & Lifestyle','Cleaning Supplies','ACTIVE'),
  ('Dairy & Breakfast','Milk','Grocery & Kirana','Dairy & Milk','ACTIVE'),
  ('Personal Care','Jewellery','Fashion & Apparel','Accessories & Jewelry','ACTIVE'),
  ('Sauces & Spreads','Honey & Chyawanprash','Grocery & Kirana','General','ACTIVE'),
  ('Instant & Frozen Food','Pasta & More','Grocery & Kirana','Ready-to-Eat','ACTIVE'),
  ('Home & Office','Bags','Home & Lifestyle','Home Essentials','ACTIVE'),
  ('Vegetables & Fruits','Certified Organic','Fresh Items','Fresh Produce','ACTIVE'),
  ('Bakery & Biscuits','Rusks & Wafers','Bakeries & Desserts','Rusks & Wafers','ACTIVE'),
  ('Masala, Oil & More','Dry Fruits','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Dairy & Breakfast','Cheese','Grocery & Kirana','Dairy & Milk','ACTIVE'),
  ('Dry Fruits, Masala & Oil','Dry Fruit Gift Packs','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Instant & Frozen Food','Frozen Veg Snacks','Grocery & Kirana','Frozen Foods','ACTIVE'),
  ('Instant & Frozen Food','Instant Mixes','Grocery & Kirana','Ready-to-Eat','ACTIVE'),
  ('Masala, Oil & More','Whole Spices','Grocery & Kirana','Masalas & Spices','ACTIVE'),
  ('Munchies','Popcorn','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Breakfast & Instant Food','Noodles','Grocery & Kirana','Ready-to-Eat','ACTIVE'),
  ('Beauty & Cosmetics','Body & Skin Care','Beauty & Personal Care','Skincare','ACTIVE'),
  ('Home & Office','Electrical Accessories','Home & Lifestyle','Home Essentials','ACTIVE'),
  ('Home & Office','Clothing, Footwear & Accessories','Home & Lifestyle','Home Essentials','ACTIVE'),
  ('Sweet Tooth','Mouth Fresheners','Bakeries & Desserts','Mouth Fresheners','ACTIVE'),
  ('Pet Care','Pet Grooming','Pet Care & Supplies','Pet Grooming','ACTIVE'),
  ('Fashion & Accessories','Women''s Sports Wear','Fashion & Apparel','Women''s Clothing','ACTIVE'),
  ('Kitchen & Dining','Storage and Containers','Home & Lifestyle','Storage & Organizers','ACTIVE'),
  ('Personal Care','Women''s Grooming','Beauty & Personal Care','Women''s Grooming','ACTIVE'),
  ('Chicken, Meat & Fish','Fish & Seafood','Fresh Items','Meat & Seafood','ACTIVE'),
  ('Sauces & Spreads','Peanut Butter','Grocery & Kirana','General','ACTIVE'),
  ('Bakery & Biscuits','Cream Biscuits','Bakeries & Desserts','Cookies & Biscuits','ACTIVE'),
  ('Paan Corner','Rolling Needs','','','PENDING_DECISION'),
  ('Tea, Coffee & Milk Drinks','Green & Flavoured Tea','Grocery & Kirana','Beverages','ACTIVE'),
  ('Toys & Games','Dolls & Accessories','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Sweet Tooth','Chocolate Gift Pack','Bakeries & Desserts','Artisanal Sweets','ACTIVE'),
  ('Baby Care','Skin & Hair Care','Pharmacy & Wellness','Baby Care','ACTIVE'),
  ('Books','Fiction Books','Stationery, Gifting & Toys','Books','ACTIVE'),
  ('Books','Comics & Mangas','Stationery, Gifting & Toys','Books','ACTIVE'),
  ('Kitchen & Dining','Barware','Home & Lifestyle','Kitchenware','ACTIVE'),
  ('Munchies','Nachos','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Instant & Frozen Food','Frozen Non-Veg Snacks','Grocery & Kirana','Frozen Foods','ACTIVE'),
  ('Munchies','Healthy Snacks','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Kitchen & Dining','Cutting & Chopping','Home & Lifestyle','Kitchenware','ACTIVE'),
  ('Stationery Needs','Glue & Tapes','Stationery, Gifting & Toys','Art & Craft Supplies','ACTIVE'),
  ('Sauces & Spreads','Jam & Spreads','Grocery & Kirana','General','ACTIVE'),
  ('Pharma & Wellness','Protein & Sports Supplements','Pharmacy & Wellness','Vitamins & Supplements','ACTIVE'),
  ('Home Furnishing & Decor','Party Essentials','Home & Lifestyle','Home Decor','ACTIVE'),
  ('Dairy & Breakfast','Muesli & Granola','Grocery & Kirana','Rice & Grains','ACTIVE'),
  ('Tea, Coffee & Milk Drinks','Cold Coffee & Ice Tea','Grocery & Kirana','Beverages','ACTIVE'),
  ('Dairy & Breakfast','Oats','Grocery & Kirana','Rice & Grains','ACTIVE'),
  ('Tea, Coffee & Health Drinks','Milk Drinks','Grocery & Kirana','Beverages','ACTIVE'),
  ('Books','Baby & Toddler Books','Stationery, Gifting & Toys','Books','ACTIVE'),
  ('Home & Office','Party Essentials','Home & Lifestyle','Home Decor','ACTIVE'),
  ('Masala, Oil & More','Oil','Grocery & Kirana','Cooking Oil & Ghee','ACTIVE'),
  ('Vegetables & Fruits','Freshly Cut & Sprouts','Fresh Items','Fresh Produce','ACTIVE'),
  ('Pharma & Wellness','Adult Diapers','Pharmacy & Wellness','Adult Incontinence','ACTIVE'),
  ('Cleaning Essentials','Dishwashing Accessories','Home & Lifestyle','Cleaning Supplies','ACTIVE'),
  ('Magazines','Business & Finance Magazines','Stationery, Gifting & Toys','Magazines','ACTIVE'),
  ('Beauty & Cosmetics','Face Cream & Gel','Beauty & Personal Care','Skincare','ACTIVE'),
  ('Baby Care','Nursing','Pharmacy & Wellness','Nursing & Lactation','ACTIVE'),
  ('Cleaning Essentials','Toilet & Bathroom Cleaners','Home & Lifestyle','Cleaning Supplies','ACTIVE'),
  ('Baby Care','Baby Food','Pharmacy & Wellness','Baby Care','ACTIVE'),
  ('Munchies','Papad & Fryums','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Personal Care','Handwash','Beauty & Personal Care','Bath & Body','ACTIVE'),
  ('Home & Office','Home & Kitchen Appliances','Home & Lifestyle','Kitchenware','ACTIVE'),
  ('Sauces & Spreads','Asian Sauces','Grocery & Kirana','General','ACTIVE'),
  ('Sauces & Spreads','Dips & Salad Dressings','Grocery & Kirana','General','ACTIVE'),
  ('Instant & Frozen Food','Dessert & Cake Mixes','Grocery & Kirana','Ready-to-Eat','ACTIVE'),
  ('Fashion & Accessories','Women''s Western Wear','Fashion & Apparel','Women''s Clothing','ACTIVE'),
  ('Personal Care','Shampoo & Conditioner','Beauty & Personal Care','Hair Care','ACTIVE'),
  ('Pharma & Wellness','Health Supplement Assortment','Pharmacy & Wellness','Vitamins & Supplements','ACTIVE'),
  ('Cleaning Essentials','Detergent Powder & Bars','Home & Lifestyle','Cleaning Supplies','ACTIVE'),
  ('Home Furnishing & Decor','Car & Bike Care','Home & Lifestyle','Home Essentials','ACTIVE'),
  ('Tea, Coffee & Health Drinks','Cold Coffee & Ice Tea','Grocery & Kirana','Beverages','ACTIVE'),
  ('Toys & Games','Guns & Blasters','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Dairy & Breakfast','Paneer & Tofu','Grocery & Kirana','Dairy & Milk','ACTIVE'),
  ('Home & Office','Sports, Fitness & Outdoors','Sports & Fitness','Sports & Outdoor Accessories','ACTIVE'),
  ('Personal Care','Shower Gels & Scrubs','Beauty & Personal Care','Bath & Body','ACTIVE'),
  ('Beauty & Cosmetics','Lipstick','Beauty & Personal Care','Makeup & Cosmetics','ACTIVE'),
  ('Personal Care','Deodorants & Powders','Beauty & Personal Care','Deodorants & Talc','ACTIVE'),
  ('Toys & Games','Pretend Playsets','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Tea, Coffee & Health Drinks','Green & Flavoured Tea','Grocery & Kirana','Beverages','ACTIVE'),
  ('Fashion and Accessories','Luggage & Travel Bags','Fashion & Apparel','Accessories & Jewelry','ACTIVE'),
  ('Beauty & Cosmetics','Nail color/paints','Beauty & Personal Care','Makeup & Cosmetics','ACTIVE'),
  ('Cleaning Essentials','Shoe Care','Home & Lifestyle','Cleaning Supplies','ACTIVE'),
  ('Bakery & Biscuits','Sweet & Salty','Bakeries & Desserts','Cookies & Biscuits','ACTIVE'),
  ('Dairy, Bread & Eggs','Bread','Grocery & Kirana','Ready-to-Eat','ACTIVE'),
  ('Organic & Premium','Snacks & Munchies','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Fashion & Accessories','Women''s Westerwear','Fashion & Apparel','Women''s Clothing','ACTIVE'),
  ('Baby Care','Baby Feeding Needs','Pharmacy & Wellness','Baby Feeding Essentials','ACTIVE'),
  ('Instant & Frozen Food','Herbs & Seasoning','Grocery & Kirana','Masalas & Spices','ACTIVE'),
  ('Electronics & Electricals','Music Instruments & Accessories','Electronics & Accessories','Earphones & Audio','ACTIVE'),
  ('Bakery & Biscuits','Healthy & Digestive','Bakeries & Desserts','Cookies & Biscuits','ACTIVE'),
  ('Cold Drinks & Juices','Water & Ice Cubes','Grocery & Kirana','Water & Ice','ACTIVE'),
  ('Personal Care','Soaps','Beauty & Personal Care','Bath & Body','ACTIVE'),
  ('Baby Care','Baby Wipes','Pharmacy & Wellness','Baby Diapers & Wipes','ACTIVE'),
  ('Baby Care','Oral & Nasal Care','Pharmacy & Wellness','Baby Care','ACTIVE'),
  ('Breakfast & Instant Food','Instant Mixes','Grocery & Kirana','Ready-to-Eat','ACTIVE'),
  ('Beauty & Cosmetics','Bath & Beauty Gifts','Beauty & Personal Care','Bath & Body','ACTIVE'),
  ('Personal Care','Hair Colour & More','Beauty & Personal Care','Hair Care','ACTIVE'),
  ('Organic & Premium','Chocolates & Candies','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Personal Care','Body Moisturizers & More','Beauty & Personal Care','Bath & Body','ACTIVE'),
  ('Paan Corner','Lighters','','','PENDING_DECISION'),
  ('Vegetables & Fruits','Hydroponic','Fresh Items','Fresh Produce','ACTIVE'),
  ('Kitchen & Dining','Kitchen Towels & Napkins','Home & Lifestyle','Cleaning Supplies','ACTIVE'),
  ('Dairy & Breakfast','Gourmet Cheese','Grocery & Kirana','Dairy & Milk','ACTIVE'),
  ('Baby Care','Baby Diapers','Pharmacy & Wellness','Baby Diapers & Wipes','ACTIVE'),
  ('Chicken, Meat & Fish','Sausage, Salami & Ham','Fresh Items','Meat & Seafood','ACTIVE'),
  ('Cleaning Essentials','Dishwashing Gels & Tablets','Home & Lifestyle','Cleaning Supplies','ACTIVE'),
  ('Pharma & Wellness','Digestive Care','Pharmacy & Wellness','Digestives & Antacids','ACTIVE'),
  ('Fashion and Accessories','Clothing Accessories','Fashion & Apparel','Accessories & Jewelry','ACTIVE'),
  ('Cold Drinks & Juices','Coconut Water','Grocery & Kirana','Beverages','ACTIVE'),
  ('Paan Corner','Cigarettes','','','PENDING_DECISION'),
  ('Masala, Oil & More','Salt, Sugar & Jaggery','Grocery & Kirana','Staples & Pulse','ACTIVE'),
  ('Baby Care','Bathing Needs','Pharmacy & Wellness','Baby Bathing Essentials','ACTIVE'),
  ('Organic & Gourmet','Chocolates & Candies','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Home & Office','Games','Home & Lifestyle','Home Essentials','ACTIVE'),
  ('Home & Office','Fresheners','Home & Lifestyle','Repellents & Fresheners','ACTIVE'),
  ('Pharma & Wellness','Pre & Post Workout','Pharmacy & Wellness','Vitamins & Supplements','ACTIVE'),
  ('Magazines','Children Magazines','Stationery, Gifting & Toys','Magazines','ACTIVE'),
  ('Toys & Games','Science & Learning','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Magazines','Health & Lifestyle Magazines','Stationery, Gifting & Toys','Magazines','ACTIVE'),
  ('Vegetables & Fruits','Flowers & Leaves','Fresh Items','Fresh Produce','ACTIVE'),
  ('Books','Children''s Activity Books','Stationery, Gifting & Toys','Books','ACTIVE'),
  ('Bakery & Biscuits','Baking Ingredients','Bakeries & Desserts','Baking Supplies & Ingredients','ACTIVE'),
  ('Vegetables & Fruits','Exotics & Premium','Fresh Items','Exotic Fruits & Greens','ACTIVE'),
  ('Masala, Oil & More','Dates & Seeds','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Toys & Games','Poker & Party Games','Stationery, Gifting & Toys','Board Games','ACTIVE'),
  ('Personal Care','Bath & Beauty Gifts','Beauty & Personal Care','Gift Sets & Kits','ACTIVE'),
  ('Chicken, Meat & Fish','Exotic Meat','Fresh Items','Meat & Seafood','ACTIVE'),
  ('Breakfast & Instant Food','Energy Bars','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Pharma & Wellness','Masks & Sanitizers','Pharmacy & Wellness','Masks & Sanitizers','ACTIVE'),
  ('Home & Office','DIY and Learning','Home & Lifestyle','Home Essentials','ACTIVE'),
  ('Dairy & Breakfast','Flakes & Kids Cereals','Grocery & Kirana','Rice & Grains','ACTIVE'),
  ('Sauces & Spreads','Table Sauces','Grocery & Kirana','General','ACTIVE'),
  ('Sauces & Spreads','Cooking Sauces & Paste','Grocery & Kirana','General','ACTIVE'),
  ('Baby Care','Baby Gifting & Toys','Pharmacy & Wellness','Baby Gear & Equipment','ACTIVE'),
  ('Magazines','Current Affairs & Business','Stationery, Gifting & Toys','Magazines','ACTIVE'),
  ('Cleaning Essentials','Floor Cleaners & More','Home & Lifestyle','Cleaning Supplies','ACTIVE'),
  ('Cold Drinks & Juices','Fruit Juices','Grocery & Kirana','Beverages','ACTIVE'),
  ('Home & Office','Repellents','Home & Lifestyle','Repellents & Fresheners','ACTIVE'),
  ('Masala, Oil & More','Ghee & Vanaspati','Grocery & Kirana','Cooking Oil & Ghee','ACTIVE'),
  ('Breakfast & Instant Food','Ready to Eat','Grocery & Kirana','Ready-to-Eat','ACTIVE'),
  ('Sauces & Spreads','Mayonnaise','Grocery & Kirana','General','ACTIVE'),
  ('Organic & Gourmet','Beverages','Grocery & Kirana','Beverages','ACTIVE'),
  ('Tea, Coffee & Health Drinks','Lactose Free Drink','Grocery & Kirana','Dairy & Milk','ACTIVE'),
  ('Baby Care','Health & Safety','Pharmacy & Wellness','Baby Care','ACTIVE'),
  ('Baby Care','Hygiene','Pharmacy & Wellness','Baby Bathing Essentials','ACTIVE'),
  ('Pharma & Wellness','Healthcare Devices','Pharmacy & Wellness','Health Monitors','ACTIVE'),
  ('Munchies','Munchies Gift Packs','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Toys & Games','Novelty Toys','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Instant & Frozen Food','Batter','Grocery & Kirana','Ready-to-Eat','ACTIVE'),
  ('Breakfast & Instant Food','Frozen Non-Veg Snacks','Grocery & Kirana','Frozen Foods','ACTIVE'),
  ('Pharma & Wellness','Condoms','Pharmacy & Wellness','Sexual Wellness','ACTIVE'),
  ('Home & Office','Home Improvement','Hardware & Plumbing','Home Improvement & Tools','ACTIVE'),
  ('Tea, Coffee & Milk Drinks','Milk Drinks','Grocery & Kirana','Beverages','ACTIVE'),
  ('Breakfast & Instant Food','Pasta','Grocery & Kirana','Ready-to-Eat','ACTIVE'),
  ('Beauty & Cosmetics','Lip Balm','Beauty & Personal Care','Makeup & Cosmetics','ACTIVE'),
  ('Atta, Rice & Dal','Other Flours','Grocery & Kirana','Atta','ACTIVE'),
  ('Toys & Games','Action Figures','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Fashion and Accessories','Jewellery','Fashion & Apparel','Accessories & Jewelry','ACTIVE'),
  ('Cleaning Essentials','Fabric Conditioner & Additives','Home & Lifestyle','Cleaning Supplies','ACTIVE'),
  ('Beauty & Cosmetics','Hair Oil','Beauty & Personal Care','Hair Care','ACTIVE'),
  ('Dairy, Bread & Eggs','Curd & Yogurt','Grocery & Kirana','Dairy & Milk','ACTIVE'),
  ('Vegetables & Fruits','Leafies & Herbs','Fresh Items','Fresh Produce','ACTIVE'),
  ('Toys & Games','Board Games','Stationery, Gifting & Toys','Board Games','ACTIVE'),
  ('Pharma & Wellness','Supplements','Pharmacy & Wellness','Vitamins & Supplements','ACTIVE'),
  ('Pharma & Wellness','Beauty Supplements','Pharmacy & Wellness','Vitamins & Supplements','ACTIVE'),
  ('Pet Care','Dog Treat','Pet Care & Supplies','Dog Food','ACTIVE'),
  ('Home & Office','Car & Bike Care','Home & Lifestyle','Home Essentials','ACTIVE'),
  ('Vegetables & Fruits','Other Frozen Snacks','Fresh Items','Fresh Produce','ACTIVE'),
  ('Baby Care','Baby Skin & Hair Care','Pharmacy & Wellness','Baby Care','ACTIVE'),
  ('Pet Care','Diverse Pet Food','Pet Care & Supplies','Toys & Accessories','ACTIVE'),
  ('Tea, Coffee & Milk Drinks','Herbal Drinks','Grocery & Kirana','Beverages','ACTIVE'),
  ('Tea, Coffee & Health Drinks','Herbal Drinks','Grocery & Kirana','Beverages','ACTIVE'),
  ('Organic & Premium','Cookies & Wafers','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Vegetables & Fruits','Vegetables','Fresh Items','Fresh Vegetables','ACTIVE'),
  ('Cleaning Essentials','Household Appliance Cleaners','Home & Lifestyle','Cleaning Supplies','ACTIVE'),
  ('Ice Cream & Frozen Desserts','Tubs','Bakeries & Desserts','Artisanal Sweets','ACTIVE'),
  ('Organic & Premium','Tea & Coffee','Grocery & Kirana','Beverages','ACTIVE'),
  ('Paan Corner','Hookah Needs','','','PENDING_DECISION'),
  ('Sauces & Spreads','Chutney & Pickle','Grocery & Kirana','General','ACTIVE'),
  ('Cold Drinks & Juices','Mango Drinks','Grocery & Kirana','Beverages','ACTIVE'),
  ('Dairy, Bread & Eggs','Peanut Butter','Grocery & Kirana','Ready-to-Eat','ACTIVE'),
  ('Tea, Coffee & Milk Drinks','Lactose Free Drink','Grocery & Kirana','Dairy & Milk','ACTIVE'),
  ('Sauces & Spreads','Tomato & Chilli Ketchup','Grocery & Kirana','General','ACTIVE'),
  ('Pharma & Wellness','Smoking Cessation','Pharmacy & Wellness','Smoking Cessation Aids','ACTIVE'),
  ('Bakery & Biscuits','Biscuit Gift Pack','Bakeries & Desserts','Cookies & Biscuits','ACTIVE'),
  ('Toys & Games','Model Toy Vehiclesme','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Toys & Games','Building & Block Toys','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Beauty & Cosmetics','Hair Removal','Beauty & Personal Care','Women''s Grooming','ACTIVE'),
  ('Pet Care','Dog Food & Treats','Pet Care & Supplies','Dog Food','ACTIVE'),
  ('Dairy, Bread & Eggs','Oats','Grocery & Kirana','Rice & Grains','ACTIVE'),
  ('Cold Drinks & Juices','Pure Juices','Grocery & Kirana','Beverages','ACTIVE'),
  ('Organic & Gourmet','Cookies & Wafers','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Organic & Premium','Noodles & Pasta','Grocery & Kirana','Ready-to-Eat','ACTIVE'),
  ('Home & Office','Festive Gifting','Pooja & Festive Needs','Festive Gifting','ACTIVE'),
  ('Organic & Premium','Premium Sauces & Spreads','Grocery & Kirana','General','ACTIVE'),
  ('Beauty & Cosmetics','Toners & Mists','Beauty & Personal Care','Skincare','ACTIVE'),
  ('Tea, Coffee & Health Drinks','Health Drinks','Grocery & Kirana','Beverages','ACTIVE'),
  ('Beauty & Cosmetics','Men''s Fragrance','Beauty & Personal Care','Men''s Grooming','ACTIVE'),
  ('Home & Office','Hair Dryer','Home & Lifestyle','Home Essentials','ACTIVE'),
  ('Ice Cream & Frozen Desserts','Sticks','Bakeries & Desserts','Artisanal Sweets','ACTIVE'),
  ('Beauty & Cosmetics','Body accessories','Beauty & Personal Care','Bath & Body','ACTIVE'),
  ('Beauty & Cosmetics','Women''s Fragrance','Beauty & Personal Care','Fragrances','ACTIVE'),
  ('Instant & Frozen Food','Frozen Veg','Grocery & Kirana','Frozen Foods','ACTIVE'),
  ('Beauty & Cosmetics','Lip Gloss','Beauty & Personal Care','Makeup & Cosmetics','ACTIVE'),
  ('Dairy & Breakfast','Butter & More','Grocery & Kirana','Dairy & Milk','ACTIVE'),
  ('Tea, Coffee & Milk Drinks','Herbal Infusion','Grocery & Kirana','Beverages','ACTIVE'),
  ('Fashion & Accessories','Kid''s Costumes','Fashion & Apparel','Kids'' Wear','ACTIVE'),
  ('Dairy, Bread & Eggs','Muesli','Grocery & Kirana','Rice & Grains','ACTIVE'),
  ('Cold Drinks & Juices','Cocktail Mixers/Tonic Waters','Grocery & Kirana','Water & Ice','ACTIVE'),
  ('Toys & Games','Art & Craft Kits','Stationery, Gifting & Toys','Art & Craft Supplies','ACTIVE'),
  ('Home & Office','Trimmers','Home & Lifestyle','Home Essentials','ACTIVE'),
  ('Bakery & Biscuits','Glucose & Marie','Bakeries & Desserts','Cookies & Biscuits','ACTIVE'),
  ('Instant & Frozen Food','Soup','Grocery & Kirana','Ready-to-Eat','ACTIVE'),
  ('Magazines','Easy Reads Magazines','Stationery, Gifting & Toys','Magazines','ACTIVE'),
  ('Baby Care','Baby Bathing Needs','Pharmacy & Wellness','Baby Bathing Essentials','ACTIVE'),
  ('Fashion and Accessories','Women''s Innerwear & Loungewear','Fashion & Apparel','Women''s Clothing','ACTIVE'),
  ('Cleaning Essentials','Toilet Cleaners & More','Home & Lifestyle','Cleaning Supplies','ACTIVE'),
  ('Books','Self Help Books','Stationery, Gifting & Toys','Books','ACTIVE'),
  ('Toys & Games','Sports Toys','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Baby Care','Mom Care Needs','Pharmacy & Wellness','Nursing & Lactation','ACTIVE'),
  ('Pharma & Wellness','Cough & Cold','Pharmacy & Wellness','Cold & Cough','ACTIVE'),
  ('Organic & Gourmet','Sauces & Spreads','Grocery & Kirana','General','ACTIVE'),
  ('Fashion & Accessories','Medicinal Scrubs & Aprons','Fashion & Apparel','Accessories & Jewelry','ACTIVE'),
  ('Pharma & Wellness','Lubricants and Enhancers','Pharmacy & Wellness','Sexual Wellness','ACTIVE'),
  ('Tea, Coffee & Health Drinks','Exotic & Flavoured Tea','Grocery & Kirana','Beverages','ACTIVE'),
  ('Cold Drinks & Juices','Cold Drink in Bottles','Grocery & Kirana','Beverages','ACTIVE'),
  ('Fashion and Accessories','Men''s Innerwear & Loungewear','Fashion & Apparel','Men''s Clothing','ACTIVE'),
  ('Home & Office','Mixer Grinders','Home & Lifestyle','Kitchenware','ACTIVE'),
  ('Toys & Games','Animal Toys','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Dairy, Bread & Eggs','Milk','Grocery & Kirana','Dairy & Milk','ACTIVE'),
  ('Toys & Games','Puzzles','Stationery, Gifting & Toys','Board Games','ACTIVE'),
  ('Chicken, Meat & Fish','Mutton','Fresh Items','Meat & Seafood','ACTIVE'),
  ('Beauty & Cosmetics','Face Accessories','Beauty & Personal Care','Tools & Accessories','ACTIVE'),
  ('Fashion & Accessories','Kid''s Innerwear & Loungewear','Fashion & Apparel','Kids'' Wear','ACTIVE'),
  ('Breakfast & Instant Food','Herbs & Seasoning','Grocery & Kirana','Masalas & Spices','ACTIVE'),
  ('Fashion and Accessories','Women''s Handbags','Fashion & Apparel','Accessories & Jewelry','ACTIVE'),
  ('Cleaning Essentials','Disinfectants','Home & Lifestyle','Cleaning Supplies','ACTIVE'),
  ('Beauty & Cosmetics','Fragrance Gift Sets','Beauty & Personal Care','Fragrances','ACTIVE'),
  ('Fashion & Accessories','Kid''s Footwear','Fashion & Apparel','Kids'' Wear','ACTIVE'),
  ('Vegetables & Fruits','Gourmet Mushroom','Fresh Items','Fresh Produce','ACTIVE'),
  ('Dairy, Bread & Eggs','Honey','Grocery & Kirana','Staples & Pulse','ACTIVE'),
  ('Vegetables & Fruits','Flowers','Fresh Items','Fresh Produce','ACTIVE'),
  ('Ice Cream & Frozen Desserts','Cups','Bakeries & Desserts','Artisanal Sweets','ACTIVE'),
  ('Bakery & Biscuits','Baking Ingredients & Mixes','Bakeries & Desserts','Baking Supplies & Ingredients','ACTIVE'),
  ('Cleaning Essentials','Dishwashing Gels & Powder','Home & Lifestyle','Cleaning Supplies','ACTIVE'),
  ('Organic & Premium','Instant Foods','Grocery & Kirana','Ready-to-Eat','ACTIVE'),
  ('Pharma & Wellness','Everyday Medicines','Pharmacy & Wellness','OTC Medicines','ACTIVE'),
  ('Pharma & Wellness','Personal Body Massagers','Pharmacy & Wellness','Health Supports & Ortho','ACTIVE'),
  ('Baby Care','Baby Gear','Pharmacy & Wellness','Baby Gear & Equipment','ACTIVE'),
  ('Cold Drinks & Juices','Beverages Gift Packs','Grocery & Kirana','Beverages','ACTIVE'),
  ('Pet Care','Cat Treats','Pet Care & Supplies','Cat Food','ACTIVE'),
  ('Beauty & Cosmetics','Hair tools & accessories','Beauty & Personal Care','Hair Accessories','ACTIVE'),
  ('Beauty & Cosmetics','Eyeliner','Beauty & Personal Care','Makeup & Cosmetics','ACTIVE'),
  ('Atta, Rice & Dal','Fresh Atta','Grocery & Kirana','Atta','ACTIVE'),
  ('Beauty & Cosmetics','Lip Tint','Beauty & Personal Care','Makeup & Cosmetics','ACTIVE'),
  ('Dairy, Bread & Eggs','Eggs','Grocery & Kirana','Dairy & Milk','ACTIVE'),
  ('Fashion and Accessories','Watches','Fashion & Apparel','Accessories & Jewelry','ACTIVE'),
  ('Specials','Print as a service','','','PENDING_DECISION'),
  ('Cleaning Essentials','Laundry Additives','Home & Lifestyle','Cleaning Supplies','ACTIVE'),
  ('Tea, Coffee & Health Drinks','Green Tea','Grocery & Kirana','Beverages','ACTIVE'),
  ('Munchies','Imported Snacks','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Tea, Coffee & Milk Drinks','Hot Chocolate','Grocery & Kirana','Beverages','ACTIVE'),
  ('Dairy & Breakfast','Vermicelli','Grocery & Kirana','Ready-to-Eat','ACTIVE'),
  ('Organic & Gourmet','Cooking Essentials','Grocery & Kirana','General','ACTIVE'),
  ('Sauces & Spreads','Dips & Spreads','Grocery & Kirana','General','ACTIVE'),
  ('Dairy, Bread & Eggs','Paneer & Tofu','Grocery & Kirana','Dairy & Milk','ACTIVE'),
  ('Cold Drinks & Juices','Mineral Water','Grocery & Kirana','Beverages','ACTIVE'),
  ('Dairy, Bread & Eggs','Poha','Grocery & Kirana','Rice & Grains','ACTIVE'),
  ('Toys & Games','Learning Toys','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Toys & Games','Light & Musical Toys','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Beauty & Cosmetics','Eye accessories','Beauty & Personal Care','Tools & Accessories','ACTIVE'),
  ('Dairy & Breakfast','Cream & Whitener','Grocery & Kirana','Dairy & Milk','ACTIVE'),
  ('Paan Corner','Non-Tobacco Blends','Grocery & Kirana','General','ACTIVE'),
  ('Beauty & Cosmetics','Eye Creams & Masks','Beauty & Personal Care','Skincare','ACTIVE'),
  ('Cleaning Essentials','Shoe Polish & Brush','Home & Lifestyle','Cleaning Supplies','ACTIVE'),
  ('Home & Office','Electric Kettles','Home & Lifestyle','Kitchenware','ACTIVE'),
  ('Dairy, Bread & Eggs','Cheese','Grocery & Kirana','Dairy & Milk','ACTIVE'),
  ('Cold Drinks & Juices','Mango Drink','Grocery & Kirana','Beverages','ACTIVE'),
  ('Beauty & Cosmetics','Hair Serum','Beauty & Personal Care','Hair Care','ACTIVE'),
  ('Vegetables & Fruits','Fruits','Fresh Items','Fresh Fruits','ACTIVE'),
  ('Home & Office','Fans','Home & Lifestyle','Home Essentials','ACTIVE'),
  ('Cold Drinks & Juices','Non-Alcoholic Drinks','Grocery & Kirana','Beverages','ACTIVE'),
  ('Cold Drinks & Juices','Cold Coffee','Grocery & Kirana','Beverages','ACTIVE'),
  ('Dairy, Bread & Eggs','Jam','Grocery & Kirana','Ready-to-Eat','ACTIVE'),
  ('Paan Corner','Paan Masala','Grocery & Kirana','General','ACTIVE'),
  ('Sauces & Spreads','Salad Dressings','Grocery & Kirana','General','ACTIVE'),
  ('Beauty & Cosmetics','Facial Kit','Beauty & Personal Care','Gift Sets & Kits','ACTIVE'),
  ('Vegetables & Fruits','Frozen Potato Snacks','Fresh Items','Fresh Produce','ACTIVE'),
  ('Beauty & Cosmetics','Nail accessories','Beauty & Personal Care','Tools & Accessories','ACTIVE'),
  ('Dairy, Bread & Eggs','Kids Cereals','Grocery & Kirana','Rice & Grains','ACTIVE'),
  ('Instant & Frozen Food','Imported Noodles & Pasta','Grocery & Kirana','Ready-to-Eat','ACTIVE'),
  ('Sweet Tooth','Syrups','Bakeries & Desserts','Syrups & Toppings','ACTIVE'),
  ('Cold Drinks & Juices','Cold Drink in a Can','Grocery & Kirana','Beverages','ACTIVE'),
  ('Dairy, Bread & Eggs','Flakes','Grocery & Kirana','Rice & Grains','ACTIVE'),
  ('Toys & Games','Remote Control Toys','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Fashion and Accessories','Men''s Westernwear','Fashion & Apparel','Men''s Clothing','ACTIVE'),
  ('Beauty & Cosmetics','Mascara','Beauty & Personal Care','Makeup & Cosmetics','ACTIVE'),
  ('Organic & Gourmet','Snacks & Munchies','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Home & Office','Soft Toys & Greeting Cards','Home & Lifestyle','Home Essentials','ACTIVE'),
  ('Toys & Games','Card Games','Stationery, Gifting & Toys','Board Games','ACTIVE'),
  ('Dairy, Bread & Eggs','Butter & More','Grocery & Kirana','Dairy & Milk','ACTIVE'),
  ('Fashion and Accessories','Men''s Sports Wear','Fashion & Apparel','Men''s Clothing','ACTIVE'),
  ('Toys & Games','Toddler & Baby Toys','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Home & Office','Iron','Home & Lifestyle','Home Essentials','ACTIVE'),
  ('Organic & Gourmet','Spices & Vinegar','Grocery & Kirana','Masalas & Spices','ACTIVE'),
  ('Pharma & Wellness','Antiseptic Liquid','Pharmacy & Wellness','First Aid','ACTIVE'),
  ('Beauty & Cosmetics','Women''s Razors & Trimmers','Beauty & Personal Care','Women''s Grooming','ACTIVE'),
  ('Baby Care','Baby''s Health & Safety Tools','Pharmacy & Wellness','Baby Care','ACTIVE'),
  ('Beauty & Cosmetics','Nail color remover','Beauty & Personal Care','Makeup & Cosmetics','ACTIVE'),
  ('Personal Care','Hand & Foot Care','Beauty & Personal Care','Bath & Body','ACTIVE'),
  ('Breakfast & Instant Food','Soup','Grocery & Kirana','Ready-to-Eat','ACTIVE'),
  ('Vegetables & Fruits','Frozen Indian Breads','Fresh Items','Fresh Produce','ACTIVE'),
  ('Vegetables & Fruits','Frozen Veg','Fresh Items','Fresh Produce','ACTIVE'),
  ('Fashion and Accessories','Belts & Wallets','Fashion & Apparel','Accessories & Jewelry','ACTIVE'),
  ('Books','Academic Books','Stationery, Gifting & Toys','Books','ACTIVE'),
  ('Pharma & Wellness','Hangover Cure','Pharmacy & Wellness','OTC Medicines','ACTIVE'),
  ('Organic & Gourmet','Noodles & Pasta','Grocery & Kirana','Ready-to-Eat','ACTIVE'),
  ('Beauty & Cosmetics','Hair Mask','Beauty & Personal Care','Hair Care','ACTIVE'),
  ('Toys & Games','Battle Toys','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Home & Office','Collectible Toy Guns & Accessories','Home & Lifestyle','Home Essentials','ACTIVE'),
  ('Home & Office','Garbage Bags','Home & Lifestyle','Cleaning Supplies','ACTIVE'),
  ('Vegetables & Fruits','Fresh Juice & Dips','Fresh Items','Fresh Produce','ACTIVE'),
  ('Books','Poetry Books','Stationery, Gifting & Toys','Books','ACTIVE'),
  ('Books','Mystery & Thriller Books','Stationery, Gifting & Toys','Books','ACTIVE'),
  ('Toys & Games','Cards, Puzzles & Board Games: Classic Entertainment for All','Stationery, Gifting & Toys','Board Games','ACTIVE'),
  ('Home & Office','Weighing Machines & Massagers','Home & Lifestyle','Home Essentials','ACTIVE'),
  ('Toys & Games','Cartoon Characters','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Dairy, Bread & Eggs','Batter','Grocery & Kirana','Ready-to-Eat','ACTIVE'),
  ('Books','Activity Books for Adults','Stationery, Gifting & Toys','Books','ACTIVE'),
  ('Fashion and Accessories','Men''s Footwear','Fashion & Apparel','Footwear','ACTIVE'),
  ('Cleaning Essentials','Dishwashing Bars & Tubs','Home & Lifestyle','Cleaning Supplies','ACTIVE'),
  ('Paan Corner','Ashtrays','','','PENDING_DECISION'),
  ('Paan Corner','Cigar','','','PENDING_DECISION'),
  ('Tea, Coffee & Health Drinks','Hot Chocolate','Grocery & Kirana','Beverages','ACTIVE'),
  ('Organic & Premium','Oil & Ghee','Grocery & Kirana','Cooking Oil & Ghee','ACTIVE'),
  ('Sauces & Spreads','Tomato & Chilli Ketchups','Grocery & Kirana','General','ACTIVE'),
  ('Cleaning Essentials','Disinfectant & More','Home & Lifestyle','Cleaning Supplies','ACTIVE'),
  ('Toys & Games','Tents & Pools','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Pet Care','Pet Litter','Pet Care & Supplies','Toys & Accessories','ACTIVE'),
  ('Dairy & Breakfast','Condensed Milk','Grocery & Kirana','Dairy & Milk','ACTIVE'),
  ('Organic & Gourmet','Breakfast & More','Grocery & Kirana','Ready-to-Eat','ACTIVE'),
  ('Organic & Gourmet','Baby Food','Grocery & Kirana','General','ACTIVE'),
  ('Beauty & Cosmetics','Lip Scrubs, Masks & Serums','Beauty & Personal Care','Skincare','ACTIVE'),
  ('Baby Care','Baby Gift Hampers','Pharmacy & Wellness','Baby Gear & Equipment','ACTIVE'),
  ('Breakfast & Instant Food','Plant Based Meat','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Pharma & Wellness','Skin Treatment','Pharmacy & Wellness','OTC Medicines','ACTIVE'),
  ('Toys & Games','Toys Gifting','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Home & Office','Toasters','Home & Lifestyle','Kitchenware','ACTIVE'),
  ('Dairy, Bread & Eggs','Vermicelli','Grocery & Kirana','Ready-to-Eat','ACTIVE'),
  ('Fashion and Accessories','Women''s Ethnic Wear','Fashion & Apparel','Women''s Clothing','ACTIVE'),
  ('Fashion and Accessories','Women''s Western Wear','Fashion & Apparel','Women''s Clothing','ACTIVE'),
  ('Beauty & Cosmetics','Hair Oil, Masks & Serums','Beauty & Personal Care','Hair Care','ACTIVE'),
  ('Books','Literature / Classics Books','Stationery, Gifting & Toys','Books','ACTIVE'),
  ('Beauty & Cosmetics','Shampoo','Beauty & Personal Care','Hair Care','ACTIVE'),
  ('Pet Care','Pet Health & Supplements','Pet Care & Supplies','Pet Health','ACTIVE'),
  ('Cold Drinks & Juices','Iced Tea','Grocery & Kirana','Beverages','ACTIVE'),
  ('Home & Office','Kids Toys & More','Home & Lifestyle','Home Essentials','ACTIVE'),
  ('Books','Religion & Spirituality Books','Stationery, Gifting & Toys','Books','ACTIVE'),
  ('Organic & Gourmet','Dairy Products','Grocery & Kirana','Dairy & Milk','ACTIVE'),
  ('Baby Care','Mom Care','Pharmacy & Wellness','Nursing & Lactation','ACTIVE'),
  ('Books','Business, Economics & Finance Books','Stationery, Gifting & Toys','Books','ACTIVE'),
  ('Cleaning Essentials','Dishwashing Bars','Home & Lifestyle','Cleaning Supplies','ACTIVE'),
  ('Organic & Gourmet','Dry Fruits, Nuts & Seeds','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Organic & Gourmet','Oil & Ghee','Grocery & Kirana','Cooking Oil & Ghee','ACTIVE'),
  ('Toys & Games','Science Project Kits','Stationery, Gifting & Toys','Art & Craft Supplies','ACTIVE'),
  ('Cold Drinks & Juices','Imported Beverages','Grocery & Kirana','Beverages','ACTIVE'),
  ('Sauces & Spreads','Honey','Grocery & Kirana','General','ACTIVE'),
  ('Beauty & Cosmetics','Hair Tools & Accessories','Beauty & Personal Care','Hair Accessories','ACTIVE'),
  ('Beauty & Cosmetics','Lip Liner','Beauty & Personal Care','Makeup & Cosmetics','ACTIVE'),
  ('Tea, Coffee & Health Drinks','Hot Chocolate Drink','Grocery & Kirana','Beverages','ACTIVE'),
  ('Sweet Tooth','Chocolate Bars','Bakeries & Desserts','Artisanal Sweets','ACTIVE'),
  ('Organic & Gourmet','Pulses & Millets','Grocery & Kirana','Dal & Pulses','ACTIVE'),
  ('Fashion and Accessories','Women''s Sports Wear','Fashion & Apparel','Women''s Clothing','ACTIVE'),
  ('Magazines','Fashion & Luxury Magazines','Stationery, Gifting & Toys','Magazines','ACTIVE'),
  ('Sauces & Spreads','Imported Spreads','Grocery & Kirana','General','ACTIVE'),
  ('Books','Romance Books','Stationery, Gifting & Toys','Books','ACTIVE'),
  ('Dairy & Breakfast','Breakfast Mixes','Grocery & Kirana','Ready-to-Eat','ACTIVE'),
  ('Sauces & Spreads','Chyawanprash','Grocery & Kirana','General','ACTIVE'),
  ('Organic & Gourmet','Flour','Grocery & Kirana','Atta','ACTIVE'),
  ('Books','Historical & Mythological Books','Stationery, Gifting & Toys','Books','ACTIVE'),
  ('Chicken, Meat & Fish','Plant Based Meat','Fresh Items','Meat & Seafood','ACTIVE'),
  ('Books','Contemporary Books','Stationery, Gifting & Toys','Books','ACTIVE'),
  ('Dairy, Bread & Eggs','Granola','Grocery & Kirana','Rice & Grains','ACTIVE'),
  ('Beauty & Cosmetics','Hair color','Beauty & Personal Care','Hair Care','ACTIVE'),
  ('Fashion and Accessories','Accessories & Gift Sets','Fashion & Apparel','Accessories & Jewelry','ACTIVE'),
  ('Tea, Coffee & Milk Drinks','Imported Tea & Coffee','Grocery & Kirana','Beverages','ACTIVE'),
  ('Fashion and Accessories','Women''s Footwear','Fashion & Apparel','Footwear','ACTIVE'),
  ('Specials','Bill Breaker','','','PENDING_DECISION'),
  ('Toys & Games','Dolls & Play Sets','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Toys & Games','Art & Craft Games','Stationery, Gifting & Toys','Art & Craft Supplies','ACTIVE'),
  ('Beauty & Cosmetics','Makeup brushes','Beauty & Personal Care','Tools & Accessories','ACTIVE'),
  ('Pharma & Wellness','Oral Health & Eye Care','Pharmacy & Wellness','OTC Medicines','ACTIVE'),
  ('Toys & Games','Rattles','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Tea, Coffee & Health Drinks','Leaf & Dust Tea','Grocery & Kirana','Beverages','ACTIVE'),
  ('Home & Office','Choppers','Home & Lifestyle','Kitchenware','ACTIVE'),
  ('Magazines','Sports & Entertainment','Stationery, Gifting & Toys','Magazines','ACTIVE'),
  ('Toys & Games','Festive Toys','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Beauty & Cosmetics','Hair Spray, Gel & Wax','Beauty & Personal Care','Hair Care','ACTIVE'),
  ('Beauty & Cosmetics','After shave','Beauty & Personal Care','Men''s Grooming','ACTIVE'),
  ('Organic & Premium','Baking Essentials','Grocery & Kirana','General','ACTIVE'),
  ('Atta, Rice & Dal','Flours','Grocery & Kirana','Atta','ACTIVE'),
  ('Books','Fantasy Books','Stationery, Gifting & Toys','Books','ACTIVE'),
  ('Organic & Gourmet','Tea & Coffee','Grocery & Kirana','Beverages','ACTIVE'),
  ('Dairy, Bread & Eggs','Cream & Whitener','Grocery & Kirana','Dairy & Milk','ACTIVE'),
  ('Dry Fruits, Masala & Oil','Whole Herbs','Grocery & Kirana','Masalas & Spices','ACTIVE'),
  ('Fashion and Accessories','Sunglasses & Eyewear','Fashion & Apparel','Accessories & Jewelry','ACTIVE'),
  ('Paan Corner','Tobacco','','','PENDING_DECISION'),
  ('Beauty & Cosmetics','Conditioners','Beauty & Personal Care','Hair Care','ACTIVE'),
  ('Cold Drinks & Juices','Soda','Grocery & Kirana','Beverages','ACTIVE'),
  ('Dairy, Bread & Eggs','Condensed Milk','Grocery & Kirana','Dairy & Milk','ACTIVE'),
  ('Beauty & Cosmetics','Blush & Highlighter','Beauty & Personal Care','Makeup & Cosmetics','ACTIVE'),
  ('Fashion and Accessories','Kid''s Footwear','Fashion & Apparel','Kids'' Wear','ACTIVE'),
  ('Magazines','Travel & Experiences Maagazines','Stationery, Gifting & Toys','Magazines','ACTIVE'),
  ('Magazines','Arts & Built Environment','Stationery, Gifting & Toys','Magazines','ACTIVE'),
  ('Specials','Freebie','','','PENDING_DECISION'),
  ('Books','Science & Technology Books','Stationery, Gifting & Toys','Books','ACTIVE'),
  ('Toys & Games','Learning & Education Toys','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Books','Subject Reference & Learning Books','Stationery, Gifting & Toys','Books','ACTIVE'),
  ('Personal Care','Bath & Body Kits','Beauty & Personal Care','Bath & Body','ACTIVE'),
  ('Ice Cream & Frozen Desserts','Sandwiches, Cakes, and Other','Bakeries & Desserts','Cakes & Pastries','ACTIVE'),
  ('Sweet Tooth','Chocolate Syrup','Bakeries & Desserts','Syrups & Toppings','ACTIVE'),
  ('Organic & Gourmet','Healthy Proteins','Grocery & Kirana','General','ACTIVE'),
  ('Organic & Gourmet','Organic Salt','Grocery & Kirana','Staples & Pulse','ACTIVE'),
  ('Toys & Games','Cube Games','Stationery, Gifting & Toys','Board Games','ACTIVE'),
  ('Toys & Games','Games for Adults','Stationery, Gifting & Toys','Board Games','ACTIVE'),
  ('Books','Health, Fitness & Nutrition Books','Stationery, Gifting & Toys','Books','ACTIVE'),
  ('Toys & Games','Writing Pad Toys, Laptop Toys & Tablet Toys','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Cold Drinks & Juices','Coldpress','Grocery & Kirana','Beverages','ACTIVE'),
  ('Fashion and Accessories','Medicinal Scrubs & Aprons','Fashion & Apparel','Accessories & Jewelry','ACTIVE'),
  ('Magazines','Automobile Magazines','Stationery, Gifting & Toys','Magazines','ACTIVE'),
  ('Home Furnishing & Decor','Gift Card','Home & Lifestyle','Home Essentials','ACTIVE'),
  ('Home Furnishing & Decor','Travel Cards','Home & Lifestyle','Home Essentials','ACTIVE'),
  ('Books','Political Books','Stationery, Gifting & Toys','Books','ACTIVE'),
  ('Beauty & Cosmetics','Concealer','Beauty & Personal Care','Makeup & Cosmetics','ACTIVE'),
  ('Books','Analysis & Strategy Books','Stationery, Gifting & Toys','Books','ACTIVE'),
  ('Grocery','Masala & Spices','Grocery & Kirana','Masalas & Spices','ACTIVE'),
  ('Organic & Gourmet','Rice & Rice Products','Grocery & Kirana','Rice & Grains','ACTIVE'),
  ('Books','Horror Books','Stationery, Gifting & Toys','Books','ACTIVE'),
  ('Toys & Games','Slime','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Cold Drinks & Juices','100% Juice','Grocery & Kirana','Beverages','ACTIVE'),
  ('Cold Drinks & Juices','Ice Cubes','Grocery & Kirana','Water & Ice','ACTIVE'),
  ('Organic & Premium','Dry Fruits, Nuts & Seeds','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Cold Drinks & Juices','Flavored Milk','Grocery & Kirana','Dairy & Milk','ACTIVE'),
  ('Baby Care','Diapers & Wipes','Pharmacy & Wellness','Baby Diapers & Wipes','ACTIVE'),
  ('Tea, Coffee & Health Drinks','Instant Coffee','Grocery & Kirana','Beverages','ACTIVE'),
  ('Books','Short Stories Books','Stationery, Gifting & Toys','Books','ACTIVE'),
  ('Books','History Books','Stationery, Gifting & Toys','Books','ACTIVE'),
  ('Sweet Tooth','Cakes and Rolls','Bakeries & Desserts','Cakes & Pastries','ACTIVE'),
  ('Beauty & Cosmetics','Foundation','Beauty & Personal Care','Makeup & Cosmetics','ACTIVE'),
  ('Packaged Food','Snacks & Farsans','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Toys & Games','Clay & Dough','Stationery, Gifting & Toys','Art & Craft Supplies','ACTIVE'),
  ('Home Furnishing & Decor','Door Mats & Carpets','Home & Lifestyle','Doormats & Rugs','ACTIVE'),
  ('Packaged Food','Biscuits & Cookies','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Grocery','Flours & Grains','Grocery & Kirana','Atta','ACTIVE'),
  ('Organic & Premium','Flour','Grocery & Kirana','Atta','ACTIVE'),
  ('Organic & Premium','Pulses & Millets','Grocery & Kirana','Dal & Pulses','ACTIVE'),
  ('Home & Kitchen','Freshener & Repellents','Home & Lifestyle','Repellents & Fresheners','ACTIVE'),
  ('Beauty & Cosmetics','Compact','Beauty & Personal Care','Makeup & Cosmetics','ACTIVE'),
  ('Books','Manga & Graphic Novels','Stationery, Gifting & Toys','Books','ACTIVE'),
  ('Beauty & Cosmetics','Lip Primer','Beauty & Personal Care','Makeup & Cosmetics','ACTIVE'),
  ('Toys & Games','Teddy Bears','Stationery, Gifting & Toys','Toys & Games','ACTIVE'),
  ('Sweet Tooth','Flavoured Yogurts','Bakeries & Desserts','Cakes & Pastries','ACTIVE'),
  ('Home & Kitchen','Tissue Paper & Napkins','Home & Lifestyle','Cleaning Supplies','ACTIVE'),
  ('Tea, Coffee & Health Drinks','Tea & Coffee Add-Ons','Grocery & Kirana','Beverages','ACTIVE'),
  ('Vegetables & Fruits','Organic & Hydroponic','Fresh Items','Fresh Produce','ACTIVE'),
  ('Personal Care & Beauty','Oral Care','Beauty & Personal Care','Oral Care','ACTIVE'),
  ('Bakery & Biscuits','Milk & White Breads','Bakeries & Desserts','Breads & Buns','ACTIVE'),
  ('Books','Science Fiction Books','Stationery, Gifting & Toys','Books','ACTIVE'),
  ('Magazines','Hobby Magazines','Stationery, Gifting & Toys','Magazines','ACTIVE'),
  ('Stationery','Notebooks / Diaries & More','Stationery, Gifting & Toys','Notebooks & Diaries','ACTIVE'),
  ('Personal Care & Beauty','Health & Wellness','Beauty & Personal Care','Skincare','ACTIVE'),
  ('Grocery','Rice & Rice Products','Grocery & Kirana','Rice & Grains','ACTIVE'),
  ('Personal Care & Beauty','Skin Care','Beauty & Personal Care','Skincare','ACTIVE'),
  ('Kitchen & Dining','Kitchen Tools & Accessories','Home & Lifestyle','Kitchenware','ACTIVE'),
  ('Tea, Coffee & Health Drinks','Filter Coffee','Grocery & Kirana','Beverages','ACTIVE'),
  ('Grocery','Dry Fruits','Grocery & Kirana','Snacks & Munchies','ACTIVE'),
  ('Seasonal & More','Beauty & Personal Care','','','PENDING_DECISION'),
  ('Dairy & Beverages','Beverages','Grocery & Kirana','Beverages','ACTIVE'),
  ('Personal Care & Beauty','Bath & Body','Beauty & Personal Care','Bath & Body','ACTIVE'),
  ('Grocery','Pulses','Grocery & Kirana','Dal & Pulses','ACTIVE'),
  ('Vegetables & Fruits','Combo Offer','Fresh Items','Fresh Produce','ACTIVE'),
  ('Sweet Tooth','Wafer Chocolates','Bakeries & Desserts','Artisanal Sweets','ACTIVE'),
  ('Fruits & Vegetables','Fruits & Vegetables','Fresh Items','Fresh Produce','ACTIVE'),
  ('Vegetables & Fruits','Combo & Recipes','Fresh Items','Fresh Produce','ACTIVE'),
  ('Bakery & Biscuits','Brown & Multigrain Breads','Bakeries & Desserts','Breads & Buns','ACTIVE')
) AS s(cat,subcat,vert,pas_subcat,status)
LEFT JOIN public."Vertical" ver ON ver.name=s.vert
LEFT JOIN public."Tier2Category" t2 ON t2.vertical_id=ver.id AND t2.name=s.pas_subcat
ON CONFLICT (source_platform,source_category,source_subcategory) DO UPDATE
  SET vertical_id=EXCLUDED.vertical_id, category_id=EXCLUDED.category_id, status=EXCLUDED.status, "updatedAt"=now();
