
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function seedOrders() {
    try {
        console.log('🌱 Seeding Orders for ALL Stores...');

        // 1. Find ALL Stores with managers
        const stores = await prisma.store.findMany({
            where: { managerId: { not: null } }
        });

        if (stores.length === 0) {
            console.error('❌ No stores found.');
            return;
        }

        console.log(`Found ${stores.length} stores. Seeding data for each...`);

        // 2. Find a Customer User (or create one)
        let user = await prisma.user.findFirst({ where: { role: 'CONSUMER' } });
        if (!user) {
            user = await prisma.user.create({
                data: {
                    email: `customer_${Date.now()}@example.com`,
                    name: 'Test Customer',
                    phone: '9999999999',
                    role: 'CONSUMER',
                    passwordHash: 'seeded_dummy_hash'
                }
            });
            console.log('Created new test customer');
        }

        for (const store of stores) {
            console.log(`\n--- Seeding for Store: ${store.name} (${store.id}) ---`);

            // 3. Find some Products or Create Tests
            let products = await prisma.storeProduct.findMany({
                where: { storeId: store.id },
                include: { product: true },
                take: 5
            });

            if (products.length === 0) {
                console.log(`⚠️ No products found in ${store.name}. Creating test products...`);

                // Need a base Product first
                let baseProduct = await prisma.product.findFirst();
                if (!baseProduct) {
                    baseProduct = await prisma.product.create({
                        data: {
                            name: 'Test Product Base',
                            category: 'Test',
                            description: 'Generated by seed script',
                            image: 'https://via.placeholder.com/150',
                            mrp: 1500
                        }
                    });
                }

                for (let j = 0; j < 5; j++) {
                    // Check if exists to avoid unique constraint
                    const existing = await prisma.storeProduct.findFirst({
                        where: { storeId: store.id, productId: baseProduct.id, variant: `Variant ${j + 1}` }
                    });

                    if (!existing) {
                        const newSp = await prisma.storeProduct.create({
                            data: {
                                storeId: store.id,
                                productId: baseProduct.id,
                                price: (j + 1) * 100,
                                stock: 50,
                                active: true,
                                variant: `Variant ${j + 1}`
                            },
                            include: { product: true }
                        });
                        products.push(newSp);
                    } else {
                        products.push(existing as any);
                    }
                }
                console.log('✅ Created/Found test store products.');
            }

            // 4. Create 10 Diversified Orders (More PENDING to survive timeout)
            const statuses = [
                'PENDING', 'PENDING', 'PENDING', // More pending
                'CONFIRMED', 'PREPARING',        // Processing
                'READY',                         // Ready
                'COMPLETED', 'CANCELLED',        // History
                'RETURN_REQUESTED', 'RETURN_APPROVED' // Returns (in History now)
            ];

            for (let i = 0; i < statuses.length; i++) {
                const status = statuses[i];
                const orderNumber = `PAS-${store.name.substring(0, 3).toUpperCase().replace(/[^A-Z]/g, 'X')}-${Math.floor(1000 + Math.random() * 9000)}`;
                const isPaid = status !== 'PENDING';

                const item = products[i % products.length];
                const quantity = Math.floor(Math.random() * 3) + 1;
                const price = item.price || 100;

                await prisma.order.create({
                    data: {
                        orderNumber,
                        userId: user.id,
                        storeId: store.id,
                        totalAmount: price * quantity,
                        status: status as any,
                        isPaid,
                        items: {
                            create: [{
                                storeProductId: item.id,
                                quantity,
                                price
                            }]
                        }
                    }
                });
                console.log(`✅ Created Order ${orderNumber} [${status}]`);
            }
        }
        console.log('\n🎉 Seeding Complete for All Stores!');

    } catch (error) {
        console.error('Seeding failed:', error);
    } finally {
        await prisma.$disconnect();
    }
}

seedOrders();
